### ISSUE TITLE
¿Cómo podría desarrollar una guía de programación de los canales de rtve?

### ISSUE THREAD

**Issue by jorgehudson97** [UlisesGascon/RTVE-API#1]
Saludos, he estado mirando tu proyecto y me ha parecido muy interesante, todo bien explicado y tal. 
Me preguntaba como se podría hacer para que accediendo a la API pudiese sacar una guía de programación de lo que están emitiendo ahora mismo y a las distintas horas del día y que se actualizase automáticamente. 

Si me puedes ayudar, es para un proyecto. Gracias de antemano y espero su respuesta, me puedes contactar a jorgehnarvaez.97@gmail.com si lo prefieres.

**Comment by UlisesGascon** [comment]
En principio entiendo que con esta API no se podría acceder a la programación de los canales.
